[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
board_build.filesystem = littlefs
board_build.partitions = default.csv
lib_deps =
    bblanchon/ArduinoJson@^7
    links2004/WebSockets@^2.4
    adafruit/DHT sensor library
    adafruit/Adafruit Unified Sensor